env:
  node: true

extends: 'eslint:recommended'

rules:
  # Possible Errors (most are enabled by extends: 'eslint:recommended')
  no-console:
    - 2
  no-unexpected-multiline:
    - 2

  # Best Practices
  block-scoped-var:
    - 2
  curly:
    - 2
  dot-notation:
    - 2
  eqeqeq:
    - 2
    - smart
  guard-for-in:
    - 2
  no-alert:
    - 2
  no-caller:
    - 2
  no-div-regex:
    - 2
  no-eval:
    - 2
  no-extend-native:
    - 2
  no-extra-bind:
    - 2
  no-floating-decimal:
    - 2
  no-implied-eval:
    - 2
  no-invalid-this:
    - 2
  no-labels:
    - 2
  no-loop-func:
    - 2
  no-multi-spaces:
    - 2
  no-native-reassign:
    - 2
  no-new-func:
    - 2
  no-new-wrappers:
    - 2
  no-octal-escape:
    - 2
  no-proto:
    - 2
  no-return-assign:
    - 2
  no-script-url:
    - 2
  no-self-compare:
    - 2
  no-sequences:
    - 2
  no-unused-expressions:
    - 2
  no-useless-call:
    - 2
  no-useless-concat:
    - 2
  no-with:
    - 2
  radix:
    - 2

  # Strict Mode
  strict:
    - 2
    - global

  # Variables
  no-shadow-restricted-names:
    - 2
  no-shadow:
    - 2
    - builtinGlobals: true
      hoist: functions
  no-undef-init:
    - 2
  no-use-before-define:
    - 2

  # Node.js
  callback-return:
    - 2
  handle-callback-err:
    - 2
  no-mixed-requires:
    - 2
  no-new-require:
    - 2
  no-path-concat:
    - 2

  # Maintainability
  comma-dangle:
    - 2
    - always-multiline

  # Stylistic Issues
  camelcase:
    - 2
    - properties: always
  comma-spacing:
    - 2
    - before: false
      after: true
  eol-last:
    - 2
  indent:
    - 2
    - 4
  keyword-spacing:
    - 2
  linebreak-style:
    - 2
    - unix
  new-cap:
    - 2
  new-parens:
    - 2
  no-array-constructor:
    - 2
  no-inline-comments:
    - 2
  no-lonely-if:
    - 2
  no-multiple-empty-lines:
    - 2
  no-new-object:
    - 2
  no-spaced-func:
    - 2
  no-trailing-spaces:
    - 2
  no-unneeded-ternary:
    - 2
  padded-blocks:
    - 2
    - never
  quotes:
    - 2
    - double
    - avoid-escape
  semi-spacing:
    - 2
    - before: false
      after: true
  semi:
    - 2
    - always
  space-before-blocks:
    - 2
    - always
  space-in-parens:
    - 2
    - never
  space-infix-ops:
    - 2
  space-unary-ops:
    - 2
  spaced-comment:
    - 2
    - always

  # Legacy
  max-len:
    - 2
    - 120
    - 4
